import DecoupledConsensus.Store.Model.Basic
import DecoupledConsensus.State.Model.Certificates

namespace DecoupledConsensus

/-! # Store Properties

Proof-free statement layer for the Section 3 store results.

The executable definitions live under `Store.Model`. This file contains the
specification vocabulary and `Prop`-valued theorem statements that are useful
to read without opening proof scripts. Concrete proofs live under
`Store.Proof`.

The order-independence statements below are deliberately the proved
extensional form (`OrderEquivalent`). They should not be read as the stronger
TeX claim that arbitrary valid processing orders over the same block set
produce equivalent stores; that replay/order machinery is not formalized yet.
-/

variable {n : ℕ}

open scoped Block

namespace Store

/-! ## History And Reachability Vocabulary -/

/-- Stores reachable by replaying successful `onBlock` calls from genesis. -/
inductive Reachable : Store n → Prop
  | genesis : Reachable (Store.genesis n)
  | onBlock {S S' : Store n} {B : Block n}
      (hS : Reachable S) (hstep : S.onBlock B = some S') : Reachable S'

/-- Transitive future relation generated by zero or more successful
    `onBlock` calls. -/
inductive Future : Store n → Store n → Prop
  | refl (S : Store n) : Future S S
  | step {S S' S'' : Store n} {B : Block n}
      (hstep : S.onBlock B = some S') (hFuture : Future S' S'') :
      Future S S''

/-- Lexicographic non-strict ordering on store justification keys
    `(height, block-id)`. -/
def KeyLE (h : ℕ) (J : Block n) (h' : ℕ) (J' : Block n) : Prop :=
  h < h' ∨ (h = h' ∧ J.id ≤ J'.id)

/-- A processed block has offered the justified checkpoint `(C, h)` as its
    post-state `(J, hj)`. -/
def ProcessedJustification (S : Store n) (C : Block n) (h : ℕ) : Prop :=
  ∃ e ∈ S.entries, e.state.J = C ∧ e.state.hj = h

/-- The scoped hash/id injectivity needed to compare an external finalization
    witness against every accepted entry in a store. -/
def IdInjectiveAgainstStore (tip : Block n) (S : Store n) : Prop :=
  ∀ e, e ∈ S.entries → Block.IdInjectiveOnAncestors tip e.block

/-- Certificate-level record for a justification event observed in an accepted
    store entry. This is proof-side history, not protocol state: it packages
    the facts needed by section-3 safety arguments when they need more than the
    executable descriptor `(entry.state.J, entry.state.hj)`. -/
structure JustificationRecord (S : Store n) (C : Block n) (h : ℕ) where
  entry : StoreEntry n
  mem : entry ∈ S.entries
  target_eq : entry.state.J = C
  height_eq : entry.state.hj = h
  target_ancestor : C ≼ entry.block
  tip_height : h < entry.height
  witness :
    (h = 0 ∧ C = Block.genesis) ∨
      JustifyQuorumWitness (votesIncluded entry.chain) C h

/-- Certificate-level record for a finality event. The witnessing chain need
    not be in the local store: Section 3 often reasons about finality observed
    on any chain and then compares it to a node-local store. -/
structure FinalizationRecord (F : Block n) (h_f : ℕ) where
  tip : Block n
  chain : Chain n tip
  target_ancestor : F ≼ tip
  final_state : (stateOf chain).F = F
  certificate : FinalizedCertificate chain F h_f target_ancestor

/-- Scoped id injectivity for comparing a finalization record with all accepted
    entries in a store. -/
def FinalizationRecord.IdInjectiveAgainstStore
    {F : Block n} {h_f : ℕ} (r : FinalizationRecord F h_f) (S : Store n) : Prop :=
  DecoupledConsensus.Store.IdInjectiveAgainstStore r.tip S

/-- Exact Section-3 no-high-justification invariant: every justification event
    represented in the accepted store history is at or below the current store
    root height. -/
def NoHighJustifications (S : Store n) : Prop :=
  ∀ {C : Block n} {h : ℕ}, ProcessedJustification S C h → h ≤ S.hj

/-- Extensional equality for the order-independent store components. The raw
    executable store keeps `entries` as a list, so two processing orders need
    not be definitionally equal even when they contain the same accepted
    `(block, chain)` entries. This predicate is the equality notion relevant
    to `viableTree` and `getConfirmed`. -/
structure OrderEquivalent (S T : Store n) : Prop where
  entries_iff : ∀ e : StoreEntry n, e ∈ S.entries ↔ e ∈ T.entries
  F_eq : S.F = T.F
  J_eq : S.J = T.J
  hj_eq : S.hj = T.hj
  hmax_eq : S.hmax = T.hmax

/-! ## Unconditional Store Statements -/

/-- Store justification height is monotone across future execution. -/
def HjMonotoneStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n}, Future S T → S.hj ≤ T.hj

/-- Store justification keys are monotone across future execution. -/
def KeyMonotoneStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n}, Future S T → KeyLE S.hj S.J T.hj T.J

/-- Once store finality reaches `S.F`, every future finalized root descends
    from it. -/
def FinalityIrreversibilityStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n}, Future S T → S.F ≼ T.F

/-- Reachable stores maintain `F ≼ J`. -/
def FAncestorJStatement (n : ℕ) : Prop :=
  ∀ {S : Store n}, Reachable S → S.F ≼ S.J

/-- Reachable stores keep the finalized root viable. -/
def FViableStatement (n : ℕ) : Prop :=
  ∀ {S : Store n}, Reachable S → S.isViableBool S.F = true

/-- The set-valued executable `getConfirmed` is nonempty on reachable stores
    and every output satisfies the candidate predicate. -/
def GetConfirmedTotalStatement (n : ℕ) : Prop :=
  ∀ {S : Store n}, Reachable S →
    ∃ B : Block n, B ∈ S.getConfirmed ∧ ConfirmedCandidate S B

/-- Future confirmed outputs always descend from the earlier finalized root. -/
def ForkChoiceConsistencyStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n} {B : Block n},
    Reachable S → Future S T → B ∈ T.getConfirmed → S.F ≼ B

/-- Reachable stores satisfy the no-high-justification invariant. -/
def NoHighJustificationsStatement (n : ℕ) : Prop :=
  ∀ {S : Store n}, Reachable S → NoHighJustifications S

/-! ## Accountable Store Statements -/

/-- A finalization certificate and a later processed justification are
    compatible unless accountable slashability has already occurred. -/
def CertChainStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S : Store n} {F C : Block n} {h_f h : ℕ},
        (rF : FinalizationRecord F h_f) →
        (rJ : JustificationRecord S C h) →
        rF.IdInjectiveAgainstStore S →
        h_f ≤ h →
        F ~ C

/-- Positive-height strict certchain form. Genesis is excluded because the
    genesis finality convention has certificate height `0` while the genesis
    state-height is `1`. -/
def CertChainStrictStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S : Store n} {F C : Block n} {h_f h : ℕ},
        (rF : FinalizationRecord F h_f) →
        (rJ : JustificationRecord S C h) →
        rF.IdInjectiveAgainstStore S →
        h_f ≠ 0 →
        h_f < h →
        F ≼ C ∧ F ≠ C

/-- Processed-finalization upgrade: after processing a descriptor `(F, h_f)`,
    future store roots descend from `F`. -/
def UpgradeStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S T : Store n},
        Reachable S → Future S T →
          ∀ {F : Block n} {h_f : ℕ},
            (rF : FinalizationRecord F h_f) →
            ProcessedJustification S F h_f →
            rF.IdInjectiveAgainstStore T →
            F ≼ T.J

/-- A processed finalized checkpoint remains viable in future stores. -/
def FinalizedViableStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S T : Store n},
        Reachable S → Future S T →
          ∀ {F : Block n} {h_f : ℕ},
            (rF : FinalizationRecord F h_f) →
            ProcessedJustification S F h_f →
            rF.IdInjectiveAgainstStore T →
            T.isViableBool F = true

/-- Local finality update acceptance, stated at the exposed store mutator. -/
def FinalityUpdateAcceptanceStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S : Store n}, Reachable S →
        ∀ {F' : Block n} {h_f : ℕ},
          (rF : FinalizationRecord F' h_f) →
          ProcessedJustification S F' h_f →
          rF.IdInjectiveAgainstStore S →
          S.F ≼ F' ∧ S.F ≠ F' →
          (S.updateFinalized F').F = F'

/-- Lock-in for any executable `getConfirmed` output. -/
def LockInStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S T : Store n},
        Reachable S → Future S T →
          ∀ {F B : Block n} {h_f : ℕ},
            (rF : FinalizationRecord F h_f) →
            ProcessedJustification S F h_f →
            rF.IdInjectiveAgainstStore T →
            B ∈ T.getConfirmed →
            F ≼ T.J ∧ T.isViableBool F = true ∧ F ≼ B

/-! ## Proved Extensional Order-Independence Statements -/

/-- Order-equivalent stores have the same `getConfirmed` membership. -/
def OrderEquivalentGetConfirmedStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n} {B : Block n},
    OrderEquivalent S T → (B ∈ S.getConfirmed ↔ B ∈ T.getConfirmed)

/-- Order-equivalent stores have the same viable-tree membership. -/
def OrderEquivalentViableTreeStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n} {B : Block n},
    OrderEquivalent S T → (B ∈ S.viableTree ↔ B ∈ T.viableTree)

end Store

end DecoupledConsensus
