import DecoupledConsensus.Store.Model.Basic
import DecoupledConsensus.State.Model.Certificates

namespace DecoupledConsensus

/-! # Store Properties

Proof-free statement layer for the Section 3 store results.

The executable definitions live under `Store.Model`. This file contains the
specification vocabulary and `Prop`-valued theorem statements that are useful
to read without opening proof scripts. Concrete proofs live under
`Store.Proof`.

Section 3's full-store order-independence claim is too strong for the
executable store: a block accepted before finality moves may remain in
`entries` even if another replay would reject it after finality moves. The
observable invariant is the live view rooted at the final store `F`, which is
what `LiveEquivalent` captures below.
-/

variable {n : ℕ}

open scoped Block

namespace Store

/-! ## History And Reachability Vocabulary -/

/-- Stores reachable by replaying successful `onBlock` calls from genesis. -/
inductive Reachable : Store n → Prop
  | genesis : Reachable (Store.genesis n)
  | onBlock {S S' : Store n} {B : Block n}
      (hS : Reachable S) (hstep : S.onBlock B = some S') : Reachable S'

/-- Transitive future relation generated by zero or more successful
    `onBlock` calls. -/
inductive Future : Store n → Store n → Prop
  | refl (S : Store n) : Future S S
  | step {S S' S'' : Store n} {B : Block n}
      (hstep : S.onBlock B = some S') (hFuture : Future S' S'') :
      Future S S''

/-- Lexicographic non-strict ordering on store justification keys
    `(height, block-id)`. -/
def KeyLE (h : ℕ) (J : Block n) (h' : ℕ) (J' : Block n) : Prop :=
  h < h' ∨ (h = h' ∧ J.id ≤ J'.id)

/-- The derived TeX state map notation `σ[B]`: the store accepts `B` and the
    returned state is the chain-computed post-state for `B`. -/
def AcceptedBlockState (S : Store n) (B : Block n) (σ : State n) : Prop :=
  ∃ chain : Chain n B, S.findChain? B = some chain ∧ stateOf chain = σ

/-- A processed block has offered the justified checkpoint `(C, h)` as its
    post-state `(J, hj)`. This is the TeX premise that a descriptor has fired
    on some chain processed by the node. -/
def ProcessedCheckpoint (S : Store n) (C : Block n) (h : ℕ) : Prop :=
  ∃ e ∈ S.entries, e.state.J = C ∧ e.state.hj = h

/-- Backwards-compatible proof-side name for `ProcessedCheckpoint`. -/
abbrev ProcessedJustification (S : Store n) (C : Block n) (h : ℕ) : Prop :=
  ProcessedCheckpoint S C h

/-- The scoped hash/id injectivity needed to compare an external finalization
    witness against every accepted entry in a store. -/
def IdInjectiveAgainstStore (tip : Block n) (S : Store n) : Prop :=
  ∀ e, e ∈ S.entries → Block.IdInjectiveOnAncestors tip e.block

/-- External finality evidence, scoped to a store's accepted entries by the
    hash/id injectivity assumption needed by the safety argument. This is the
    TeX premise "block `F` is finalized at height `h_f`", plus the local
    collision-freedom assumption for the block histories being compared. -/
def FinalizedWithStoreIds (F : Block n) (h_f : ℕ) (S : Store n) : Prop :=
  ∃ tip : Block n, ∃ chain : Chain n tip, ∃ hF : F ≼ tip,
    (stateOf chain).F = F ∧
      FinalizedCertificate chain F h_f hF ∧
      IdInjectiveAgainstStore tip S

/-- Exact Section-3 no-high-justification invariant: every justification event
    represented in the accepted store history is at or below the current store
    root height. -/
def NoHighJustifications (S : Store n) : Prop :=
  ∀ {C : Block n} {h : ℕ}, ProcessedCheckpoint S C h → h ≤ S.hj

/-- Extensional equality for the order-independent store components. The raw
    executable store keeps `entries` as a list, so two processing orders need
    not be definitionally equal even when they contain the same accepted
    `(block, chain)` entries. This predicate is the equality notion relevant
    to `viableTree` and `getConfirmed`. -/
structure OrderEquivalent (S T : Store n) : Prop where
  entries_iff : ∀ e : StoreEntry n, e ∈ S.entries ↔ e ∈ T.entries
  F_eq : S.F = T.F
  J_eq : S.J = T.J
  hj_eq : S.hj = T.hj
  hmax_eq : S.hmax = T.hmax

/-- Entry-level agreement for a block in the live subtree. The transferred
    entry must carry the same block and state-height, which is enough for the
    executable height filter and confirmed-output tests. -/
def EntryAcceptedIn (S : Store n) (e : StoreEntry n) : Prop :=
  ∃ e' ∈ S.entries, e'.block = e.block ∧ e'.height = e.height

/-- Entry-level agreement for a block in the live subtree. -/
def HasMatchingEntry (_S T : Store n) (e : StoreEntry n) : Prop :=
  ∃ e' ∈ T.entries, e'.block = e.block ∧ e'.height = e.height

/-- A replay order/list produced the final store by attempting every block and
    ignoring failed `onBlock` calls. -/
def ReplayOf (blocks : List (Block n)) (S : Store n) : Prop :=
  S = Store.replayBlocks blocks

/-- Replay over proof-side input entries, using only their block payloads for
    execution. The entry state/height is available to canonical-summary proofs
    but is not extra executable protocol state. -/
def ReplayEntriesOf (input : List (StoreEntry n)) (S : Store n) : Prop :=
  ReplayOf (input.map StoreEntry.block) S

/-- A block is ready once its parent is already in the replay prefix. Genesis is
    always ready. -/
def ParentReadyIn (seen : List (Block n)) : Block n → Prop
  | Block.genesis => True
  | Block.mk _ parent _ _ => parent = Block.genesis ∨ parent ∈ seen

/-- Parent-first replay order, parameterized by the prefix already processed. -/
def ParentFirstFrom (seen blocks : List (Block n)) : Prop :=
  match blocks with
  | [] => True
  | B :: rest => ParentReadyIn seen B ∧ ParentFirstFrom (seen ++ [B]) rest

/-- A replay list is parent-first when every non-genesis block appears after its
    parent. Genesis is treated as already available because the store starts
    from `Store.genesis`. -/
def ParentFirst (blocks : List (Block n)) : Prop :=
  ParentFirstFrom [Block.genesis] blocks

/-- Parent-first replay order for proof-side input entries. -/
def ParentFirstEntries (input : List (StoreEntry n)) : Prop :=
  ParentFirst (input.map StoreEntry.block)

/-- Blocks relevant to the observable final view are exactly the descendants of
    the final root plus the prefix leading to that root. -/
def RelevantToFinal (F B : Block n) : Prop :=
  F ≼ B ∨ B ≼ F

/-- Canonical observable summary for a replay input. The component proofs
    should identify these fields from the available block set alone. -/
structure LiveSummary (n : ℕ) where
  F : Block n
  J : Block n
  hj : ℕ
  hmax : ℕ

/-- An accepted entry is represented either by implicit genesis or by a
    proof-side input entry with the same block and derived state height. Genesis
    is implicit because every executable replay starts from `Store.genesis`, even
    if the available block list omits it. -/
def HasInputEntry (input : List (StoreEntry n)) (e : StoreEntry n) : Prop :=
  e.block = Block.genesis ∨
    ∃ a ∈ input, a.block = e.block ∧ a.height = e.height

/-- Two replay inputs carry the same available block/state-height content,
    with genesis implicit on both sides. This is the set-like equality notion
    used for comparing two different parent-first orders. -/
def InputEquivalent (input₁ input₂ : List (StoreEntry n)) : Prop :=
  ∀ e : StoreEntry n, HasInputEntry input₁ e ↔ HasInputEntry input₂ e

/-- Two replay inputs carry the same available block set. This is the public
    order-independence equivalence; entry-level state heights are recovered
    from the deterministic block state transition in proofs. -/
def InputBlockEquivalent (input₁ input₂ : List (StoreEntry n)) : Prop :=
  ∀ B : Block n, B ∈ input₁.map StoreEntry.block ↔
    B ∈ input₂.map StoreEntry.block

/-- Scoped hash/id injectivity for every pair of histories considered by an
    order-independence input. Genesis is implicit, matching `HasInputEntry`. -/
def InputIdInjective (input : List (StoreEntry n)) : Prop :=
  ∀ e a : StoreEntry n, HasInputEntry input e → HasInputEntry input a →
    Block.IdInjectiveOnAncestors e.block a.block

/-- A possible final store root determined by the common replay input. Genesis
    is always a candidate because every replay starts from the genesis store. -/
def FinalityCandidate (input : List (StoreEntry n)) (F : Block n) : Prop :=
  F = Block.genesis ∨ ∃ e ∈ input, e.state.F = F

/-- `Fmax` is the greatest finalized root appearing in the input post-states
    (with genesis included). Under the accountable-safety assumptions these
    candidates form a chain; this predicate records the resulting maximum. -/
def FinalityMax (input : List (StoreEntry n)) (Fmax : Block n) : Prop :=
  FinalityCandidate input Fmax ∧
    ∀ F, FinalityCandidate input F → F ≼ Fmax

/-- A possible store frontier height determined by the common replay input.
    Genesis contributes height `1` even when it is omitted from the available
    block list. -/
def HeightCandidate (input : List (StoreEntry n)) (h : ℕ) : Prop :=
  h = 1 ∨ ∃ e ∈ input, e.height = h

/-- `hmax` is the maximum post-state height appearing in the replay input,
    with the implicit genesis height included. -/
def HeightMax (input : List (StoreEntry n)) (hmax : ℕ) : Prop :=
  HeightCandidate input hmax ∧
    ∀ h, HeightCandidate input h → h ≤ hmax

/-- A possible live justification key determined by the common replay input.
    Only targets descending from the canonical finalized root are relevant:
    off-final-subtree blocks may be accepted in one replay order and rejected
    in another, but they cannot affect confirmed outputs after finality roots
    at `F`. -/
def JustificationCandidate
    (input : List (StoreEntry n)) (F J : Block n) (h : ℕ) : Prop :=
  F ≼ J ∧
    ((J = Block.genesis ∧ h = 0) ∨
      ∃ e ∈ input, e.state.J = J ∧ e.state.hj = h)

/-- Lexicographically maximal live justification key in the common input.
    The ordering matches the executable `updateJustified` tie-breaker. -/
def JustificationMax
    (input : List (StoreEntry n)) (F Jmax : Block n) (hjmax : ℕ) : Prop :=
  JustificationCandidate input F Jmax hjmax ∧
    ∀ J h, JustificationCandidate input F J h → KeyLE h J hjmax Jmax

/-- Canonical live summary induced by one replay input. The fields are
    specified extensionally, not computed by the store. -/
def LiveSummaryMatches (input : List (StoreEntry n)) (summary : LiveSummary n) :
    Prop :=
  FinalityMax input summary.F ∧
    JustificationMax input summary.F summary.J summary.hj ∧
    HeightMax input summary.hmax

/-- The component invariant needed for observable order independence.

    This is the intended target for the replay proof: prove each field from
    the common input set (`F`, `J`, `hj`, `hmax`) and prove that the live
    subtree rooted at canonical `F` is exactly the common input's live subtree.
    Unlike `LiveEquivalent`, this predicate is one-store-at-a-time, so the
    component lemmas can be proved independently and then combined. -/
structure LiveComplete (input : List (StoreEntry n)) (summary : LiveSummary n)
    (S : Store n) : Prop where
  reachable : Reachable S
  F_eq : S.F = summary.F
  J_eq : S.J = summary.J
  hj_eq : S.hj = summary.hj
  hmax_eq : S.hmax = summary.hmax
  live_input_accepted :
    ∀ e : StoreEntry n, e ∈ input → summary.F ≼ e.block → EntryAcceptedIn S e
  live_entries_from_input :
    ∀ e : StoreEntry n, e ∈ S.entries → S.F ≼ e.block → HasInputEntry input e

/-- Equivalence of the observable store view rooted at finality.

    The raw accepted-entry lists may differ outside the subtree of `F`; those
    blocks are unobservable to `getConfirmed`. Entries descending from the
    final root must match in both directions, with their derived state-heights
    preserved. -/
structure LiveEquivalent (S T : Store n) : Prop where
  F_eq : S.F = T.F
  J_eq : S.J = T.J
  hj_eq : S.hj = T.hj
  hmax_eq : S.hmax = T.hmax
  live_entries_forward :
    ∀ e : StoreEntry n, e ∈ S.entries → S.F ≼ e.block → HasMatchingEntry S T e
  live_entries_backward :
    ∀ e : StoreEntry n, e ∈ T.entries → T.F ≼ e.block → HasMatchingEntry T S e

/-! ## Unconditional Store Statements -/

/-- Store justification height is monotone across future execution. -/
def HjMonotoneStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n}, Future S T → S.hj ≤ T.hj

/-- Store justification keys are monotone across future execution. -/
def KeyMonotoneStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n}, Future S T → KeyLE S.hj S.J T.hj T.J

/-- Once store finality reaches `S.F`, every future finalized root descends
    from it. -/
def FinalityIrreversibilityStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n}, Future S T → S.F ≼ T.F

/-- Reachable stores maintain `F ≼ J`. -/
def FAncestorJStatement (n : ℕ) : Prop :=
  ∀ {S : Store n}, Reachable S → S.F ≼ S.J

/-- Reachable stores keep the finalized root viable. -/
def FViableStatement (n : ℕ) : Prop :=
  ∀ {S : Store n}, Reachable S → S.isViableBool S.F = true

/-- The set-valued executable `getConfirmed` is nonempty on reachable stores
    and every output satisfies the candidate predicate. -/
def GetConfirmedTotalStatement (n : ℕ) : Prop :=
  ∀ {S : Store n}, Reachable S →
    (∃ B : Block n, B ∈ S.getConfirmed) ∧
      ∀ {B : Block n}, B ∈ S.getConfirmed → ConfirmedCandidate S B

/-- Future confirmed outputs always descend from the earlier finalized root. -/
def ForkChoiceConsistencyStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n} {B : Block n},
    Reachable S → Future S T → B ∈ T.getConfirmed → S.F ≼ B

/-- Reachable stores satisfy the no-high-justification invariant. -/
def NoHighJustificationsStatement (n : ℕ) : Prop :=
  ∀ {S : Store n}, Reachable S → NoHighJustifications S

/-! ## Accountable Store Statements -/

/-- A finalization certificate and a later processed justification are
    compatible unless accountable slashability has already occurred. -/
def CertChainStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S : Store n} {F C : Block n} {h_f h : ℕ},
        FinalizedWithStoreIds F h_f S →
        ProcessedCheckpoint S C h →
        h_f ≤ h →
        F ~ C

/-- Positive-height strict certchain form. Genesis is excluded because the
    genesis finality convention has certificate height `0` while the genesis
    state-height is `1`. -/
def CertChainStrictStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S : Store n} {F C : Block n} {h_f h : ℕ},
        FinalizedWithStoreIds F h_f S →
        ProcessedCheckpoint S C h →
        h_f ≠ 0 →
        h_f < h →
        F ≼ C ∧ F ≠ C

/-- Processed-finalization upgrade: after processing a descriptor `(F, h_f)`,
    future store roots descend from `F`. -/
def UpgradeStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S T : Store n},
        Reachable S → Future S T →
          ∀ {F : Block n} {h_f : ℕ},
            FinalizedWithStoreIds F h_f T →
            ProcessedCheckpoint S F h_f →
            F ≼ T.J

/-- A processed finalized checkpoint remains viable in future stores. -/
def FinalizedViableStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S T : Store n},
        Reachable S → Future S T →
          ∀ {F : Block n} {h_f : ℕ},
            FinalizedWithStoreIds F h_f T →
            ProcessedCheckpoint S F h_f →
            T.isViableBool F = true

/-- Local finality update acceptance, stated at the exposed store mutator. -/
def FinalityUpdateAcceptanceStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S : Store n}, Reachable S →
        ∀ {F' : Block n} {h_f : ℕ},
          FinalizedWithStoreIds F' h_f S →
          ProcessedCheckpoint S F' h_f →
          S.F ≼ F' ∧ S.F ≠ F' →
          (S.updateFinalized F').F = F'

/-- Local finality update acceptance in monotone form: if the old finalized
    root is comparable with the processed finalized candidate, the result is
    at or beyond that candidate. -/
def FinalityUpdateDescendsStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S : Store n}, Reachable S →
        ∀ {F' : Block n} {h_f : ℕ},
          FinalizedWithStoreIds F' h_f S →
          ProcessedCheckpoint S F' h_f →
          (F' ≼ S.F ∨ (S.F ≼ F' ∧ S.F ≠ F')) →
          F' ≼ (S.updateFinalized F').F

/-- `onBlock`-level finality update acceptance for fresh blocks. This is the
    direct section-3 surface: if the processed block state `σ[B]` finalizes a
    strict descendant of the old store-finalized root, the resulting store has
    `F = σ[B].F`. Duplicate replays are excluded because they are an
    executable convenience, not a TeX block-processing step. -/
def OnBlockFinalityUpdateAcceptanceStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S S' : Store n} {B : Block n} {σB : State n},
        Reachable S →
          S.containsBlockBool B = false →
          S.onBlock B = some S' →
          AcceptedBlockState S' B σB →
          IdInjectiveAgainstStore B S' →
          S.F ≼ σB.F ∧ S.F ≠ σB.F →
          S'.F = σB.F

/-- Monotone `onBlock` form: for a fresh processed block, if the block-state
    finalized root is comparable with the previous store-finalized root, the
    resulting store finality is at or beyond that block-state root. -/
def OnBlockFinalityUpdateDescendsStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S S' : Store n} {B : Block n} {σB : State n},
        Reachable S →
          S.containsBlockBool B = false →
          S.onBlock B = some S' →
          AcceptedBlockState S' B σB →
          IdInjectiveAgainstStore B S' →
          (σB.F ≼ S.F ∨ (S.F ≼ σB.F ∧ S.F ≠ σB.F)) →
          σB.F ≼ S'.F

/-- Lock-in for any executable `getConfirmed` output. -/
def LockInStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S T : Store n},
        Reachable S → Future S T →
          ∀ {F B : Block n} {h_f : ℕ},
            FinalizedWithStoreIds F h_f T →
            ProcessedCheckpoint S F h_f →
            B ∈ T.getConfirmed →
            F ≼ T.J ∧ T.isViableBool F = true ∧ F ≼ B

/-! ## Proved Extensional Store-Output Invariance -/

/-- Order-equivalent stores have the same `getConfirmed` membership.
    This is the proved extensional consequence of order-independence, not the
    full replay theorem from the TeX. -/
def OrderEquivalentGetConfirmedStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n} {B : Block n},
    OrderEquivalent S T → (B ∈ S.getConfirmed ↔ B ∈ T.getConfirmed)

/-- Order-equivalent stores have the same viable-tree membership.
    This is the proved extensional consequence of order-independence, not the
    full replay theorem from the TeX. -/
def OrderEquivalentViableTreeStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n} {B : Block n},
    OrderEquivalent S T → (B ∈ S.viableTree ↔ B ∈ T.viableTree)

/-! ## Live Store-Output Invariance -/

/-- Live-equivalent reachable stores have the same `getConfirmed` membership.
    This is the order-independence consequence compatible with pruning/rejecting
    irrelevant blocks outside the finalized subtree. -/
def LiveEquivalentGetConfirmedStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n} {B : Block n},
    Reachable S → Reachable T →
      LiveEquivalent S T → (B ∈ S.getConfirmed ↔ B ∈ T.getConfirmed)

/-- Shared live completeness over a common input implies equal `getConfirmed`
    membership. Parent-first replay completeness below discharges this
    component invariant for executable replays. -/
def LiveCompleteGetConfirmedStatement (n : ℕ) : Prop :=
  ∀ {input : List (StoreEntry n)} {summary : LiveSummary n}
      {S T : Store n} {B : Block n},
    LiveComplete input summary S →
      LiveComplete input summary T →
        (B ∈ S.getConfirmed ↔ B ∈ T.getConfirmed)

/-- Parent-first replay computes the canonical live summary for its input. -/
def ParentFirstReplayLiveCompleteStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {input : List (StoreEntry n)} {summary : LiveSummary n}
          {S : Store n},
        ReplayEntriesOf input S →
          ParentFirstEntries input →
          (input.map StoreEntry.block).Nodup →
          Block.genesis ∉ input.map StoreEntry.block →
          InputIdInjective input →
          LiveSummaryMatches input summary →
          LiveComplete input summary S

/-- Observable order independence for the live store view: two parent-first
    replays of the same block set agree on `F`, `J`, `hj`, `hmax`, and on the
    accepted subtree rooted at finality. They may still differ outside that
    subtree. -/
def ParentFirstReplayLiveEquivalentStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {input₁ input₂ : List (StoreEntry n)} {S T : Store n},
        ReplayEntriesOf input₁ S →
          ReplayEntriesOf input₂ T →
          ParentFirstEntries input₁ →
          ParentFirstEntries input₂ →
          (input₁.map StoreEntry.block).Nodup →
          (input₂.map StoreEntry.block).Nodup →
          Block.genesis ∉ input₁.map StoreEntry.block →
          Block.genesis ∉ input₂.map StoreEntry.block →
          InputIdInjective input₁ →
          InputBlockEquivalent input₁ input₂ →
          LiveEquivalent S T

/-- Observable order independence for two parent-first replays of equivalent
    input sets. The raw stores may differ outside the finalized subtree; the
    executable `getConfirmed` set does not. -/
def ParentFirstReplayGetConfirmedStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {input₁ input₂ : List (StoreEntry n)} {S T : Store n} {B : Block n},
        ReplayEntriesOf input₁ S →
          ReplayEntriesOf input₂ T →
          ParentFirstEntries input₁ →
          ParentFirstEntries input₂ →
          (input₁.map StoreEntry.block).Nodup →
          (input₂.map StoreEntry.block).Nodup →
          Block.genesis ∉ input₁.map StoreEntry.block →
          Block.genesis ∉ input₂.map StoreEntry.block →
          InputIdInjective input₁ →
          InputBlockEquivalent input₁ input₂ →
          (B ∈ S.getConfirmed ↔ B ∈ T.getConfirmed)

end Store

end DecoupledConsensus
