import DecoupledConsensus.Store.Model.Basic
import DecoupledConsensus.State.Model.Certificates

namespace DecoupledConsensus

/-! # Store Theorem Statements

Proof-free statement layer for the fork-choice store (paper §"Fork-choice store",
`sec:store`).

Reference paper: `height_filter_and_timeouts.tex`. A definition/theorem-level
paper↔Lean correspondence is in `docs/model-annotation.md`.

The executable definitions live under `Store.Model`. This file contains the
specification vocabulary and public-facing `Prop`-valued theorem/corollary
statements that are useful to read without opening proof scripts. Proof-internal
lemma statements and proof-decomposition predicates live under `Store.Proof`;
`Store.ProvenTheorems` gives the proved public facade.

The eight public statements under "Public Store Theorem Statements" map onto the
paper's store theorems: `FinalityIrreversibilityStatement` (`thm:finperm`),
`FAncestorJStatement` (`thm:fleqr`), `GetConfirmedTotalStatement`
(`cor:getConfirmed-total`), `ForkChoiceConsistencyStatement` (`thm:fcconsistency`),
`LocalFinalityUpdateStatement` (`thm:finlive`), `LockInStatement` (`thm:lockin`),
and the two replay statements (`thm:orderindep`).

Section 3's full-store order-independence claim is too strong for the
executable store: a block accepted before finality moves may remain in
`entries` even if another replay would reject it after finality moves. The
observable invariant is the live view rooted at the final store `F`, which is
what `LiveEquivalent` captures below.
-/

variable {n : ℕ}

open scoped Block

namespace Store

/-! ## History And Reachability Vocabulary -/

/-- Stores reachable from genesis after omitting no-op `onBlock` attempts. The
    constructor records the internal accepted transition; failed acceptance is
    observationally just the same store. -/
inductive Reachable : Store n → Prop
  | genesis : Reachable (Store.genesis n)
  | onBlock {S S' : Store n} {B : Block n}
      (hS : Reachable S) (hstep : S.acceptBlock? B = some S') : Reachable S'

/-- Transitive future relation generated by zero or more accepted store
    transitions; no-op `onBlock` attempts can always be omitted. -/
inductive Future : Store n → Store n → Prop
  | refl (S : Store n) : Future S S
  | step {S S' S'' : Store n} {B : Block n}
      (hstep : S.acceptBlock? B = some S') (hFuture : Future S' S'') :
      Future S S''

/-- Lexicographic non-strict ordering on store justification keys
    `(height, block-id)`. *(Proof-internal helper, used only under `Store.Proof`; not
    part of the public theorem surface.)* -/
def KeyLE (h : ℕ) (J : Block n) (h' : ℕ) (J' : Block n) : Prop :=
  h < h' ∨ (h = h' ∧ J.id ≤ J'.id)

/-- The derived TeX state map notation `σ[B]`: the store accepts `B` and the
    returned state is the chain-computed post-state for `B`. -/
def AcceptedBlockState (S : Store n) (B : Block n) (σ : State n) : Prop :=
  ∃ chain : Chain n B, S.findChain? B = some chain ∧ stateOf chain = σ

/-- A processed block has offered the justified checkpoint `(C, h)` as its
    post-state `(J, hj)`. This is the TeX premise that a descriptor has fired
    on some chain processed by the node. -/
def ProcessedCheckpoint (S : Store n) (C : Block n) (h : ℕ) : Prop :=
  ∃ e ∈ S.entries, e.state.J = C ∧ e.state.hj = h

/-- Backwards-compatible proof-side alias for `ProcessedCheckpoint`. *(Proof-internal
    helper, used only under `Store.Proof`; not part of the public theorem surface.)* -/
abbrev ProcessedJustification (S : Store n) (C : Block n) (h : ℕ) : Prop :=
  ProcessedCheckpoint S C h

/-- The scoped hash/id injectivity needed to compare an external finalization
    witness against every accepted entry in a store. -/
def IdInjectiveAgainstStore (tip : Block n) (S : Store n) : Prop :=
  ∀ e, e ∈ S.entries → Block.IdInjectiveOnAncestors tip e.block

/-- External finality evidence, scoped to a store's accepted entries by the
    hash/id injectivity assumption needed by the safety argument. This is the
    TeX premise "block `F` is finalized at height `h_f`", plus the local
    collision-freedom assumption for the block histories being compared. -/
def FinalizedWithStoreIds (F : Block n) (h_f : ℕ) (S : Store n) : Prop :=
  ∃ tip : Block n, ∃ chain : Chain n tip, ∃ hF : F ≼ tip,
    (stateOf chain).F = F ∧
      FinalizedCertificate chain F h_f hF ∧
      IdInjectiveAgainstStore tip S

/-- No-high-justification invariant (paper Lemma `lem:no-high-just`): every
    justification event represented in the accepted store history is at or below the
    current store root height. *(Proof-internal helper consumed by the `LockIn` proof
    chain under `Store.Proof`; not exported as a public theorem statement.)* -/
def NoHighJustifications (S : Store n) : Prop :=
  ∀ {C : Block n} {h : ℕ}, ProcessedCheckpoint S C h → h ≤ S.hj

/-- Entry-level agreement for a block in the live subtree. -/
def HasMatchingEntry (_S T : Store n) (e : StoreEntry n) : Prop :=
  ∃ e' ∈ T.entries, e'.block = e.block ∧ e'.height = e.height

/-- A replay order/list produced the final store by folding total `onBlock`;
    failed acceptance attempts are store no-ops. -/
def ReplayOf (blocks : List (Block n)) (S : Store n) : Prop :=
  S = Store.replayBlocks blocks

/-- Replay over proof-side input entries, using only their block payloads for
    execution. The entry state/height is available to canonical-summary proofs
    but is not extra executable protocol state. -/
def ReplayEntriesOf (input : List (StoreEntry n)) (S : Store n) : Prop :=
  ReplayOf (input.map StoreEntry.block) S

/-- A block is ready once its parent is already in the replay prefix. Genesis is
    always ready. -/
def ParentReadyIn (seen : List (Block n)) : Block n → Prop
  | Block.genesis => True
  | Block.mk _ parent _ _ => parent = Block.genesis ∨ parent ∈ seen

/-- Parent-first replay order, parameterized by the prefix already processed. -/
def ParentFirstFrom (seen blocks : List (Block n)) : Prop :=
  match blocks with
  | [] => True
  | B :: rest => ParentReadyIn seen B ∧ ParentFirstFrom (seen ++ [B]) rest

/-- A replay list is parent-first when every non-genesis block appears after its
    parent. Genesis is treated as already available because the store starts
    from `Store.genesis`. -/
def ParentFirst (blocks : List (Block n)) : Prop :=
  ParentFirstFrom [Block.genesis] blocks

/-- Parent-first replay order for proof-side input entries. -/
def ParentFirstEntries (input : List (StoreEntry n)) : Prop :=
  ParentFirst (input.map StoreEntry.block)

/-- An accepted entry is represented either by implicit genesis or by a
    proof-side input entry with the same block and derived state height. Genesis
    is implicit because every executable replay starts from `Store.genesis`, even
    if the available block list omits it. -/
def HasInputEntry (input : List (StoreEntry n)) (e : StoreEntry n) : Prop :=
  e.block = Block.genesis ∨
    ∃ a ∈ input, a.block = e.block ∧ a.height = e.height

/-- Two replay inputs carry the same available block set. This is the public
    order-independence equivalence; entry-level state heights are recovered
    from the deterministic block state transition in proofs. -/
def InputBlockEquivalent (input₁ input₂ : List (StoreEntry n)) : Prop :=
  ∀ B : Block n, B ∈ input₁.map StoreEntry.block ↔
    B ∈ input₂.map StoreEntry.block

/-- Scoped hash/id injectivity for every pair of histories considered by an
    order-independence input. Genesis is implicit, matching `HasInputEntry`. -/
def InputIdInjective (input : List (StoreEntry n)) : Prop :=
  ∀ e a : StoreEntry n, HasInputEntry input e → HasInputEntry input a →
    Block.IdInjectiveOnAncestors e.block a.block

/-- Equivalence of the observable store view rooted at finality.

    The raw accepted-entry lists may differ outside the subtree of `F`; those
    blocks are unobservable to `getConfirmed`. Entries descending from the
    final root must match in both directions, with their derived state-heights
    preserved. -/
structure LiveEquivalent (S T : Store n) : Prop where
  F_eq : S.F = T.F
  J_eq : S.J = T.J
  hj_eq : S.hj = T.hj
  hmax_eq : S.hmax = T.hmax
  live_entries_forward :
    ∀ e : StoreEntry n, e ∈ S.entries → S.F ≼ e.block → HasMatchingEntry S T e
  live_entries_backward :
    ∀ e : StoreEntry n, e ∈ T.entries → T.F ≼ e.block → HasMatchingEntry T S e

/-! ## Public Store Theorem Statements -/

/-- **Local irreversibility of finality** (paper Theorem `thm:finperm`). Once store
    finality reaches `S.F`, every future finalized root descends from it. -/
def FinalityIrreversibilityStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n}, Future S T → S.F ≼ T.F

/-- **`F ≼ J`** (paper Theorem `thm:fleqr`). Reachable stores maintain `F ≼ J`. -/
def FAncestorJStatement (n : ℕ) : Prop :=
  ∀ {S : Store n}, Reachable S → S.F ≼ S.J

/-- **`getConfirmed` is total** (paper Corollary `cor:getConfirmed-total`). The
    set-valued executable `getConfirmed` is nonempty on reachable stores and every
    output satisfies the candidate predicate (viable, at σ-height ≥ hmax − 1). -/
def GetConfirmedTotalStatement (n : ℕ) : Prop :=
  ∀ {S : Store n}, Reachable S →
    (∃ B : Block n, B ∈ S.getConfirmed) ∧
      ∀ {B : Block n}, B ∈ S.getConfirmed → ConfirmedCandidate S B

/-- **Fork-choice consistency** (paper Theorem `thm:fcconsistency`). Future confirmed
    outputs always descend from the earlier finalized root. -/
def ForkChoiceConsistencyStatement (n : ℕ) : Prop :=
  ∀ {S T : Store n} {B : Block n},
    Reachable S → Future S T → B ∈ T.getConfirmed → S.F ≼ B

/-- **Local acceptance of finality updates** (paper Theorem `thm:finlive`), stated at
    the accepted `onBlock` transition surface. For a fresh processed block, if its
    block-state finalized root is comparable with the previous store-finalized root,
    the resulting store finality is at or beyond that block-state root. -/
def LocalFinalityUpdateStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S S' : Store n} {B : Block n} {σB : State n},
        Reachable S →
          S.containsBlockBool B = false →
          S.acceptBlock? B = some S' →
          AcceptedBlockState S' B σB →
          IdInjectiveAgainstStore B S' →
          (σB.F ≼ S.F ∨ (S.F ≼ σB.F ∧ S.F ≠ σB.F)) →
          σB.F ≼ S'.F

/-- **Lock-in** (paper Theorem `thm:lockin`) for any executable `getConfirmed` output:
    once `F` is finalized and a block carrying `(J, hj) = (F, h_f)` has been processed,
    then forever after `F ≼ J`, `F` is viable, and every `getConfirmed` output descends
    from `F`. -/
def LockInStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {S T : Store n},
        Reachable S → Future S T →
          ∀ {F B : Block n} {h_f : ℕ},
            FinalizedWithStoreIds F h_f T →
            ProcessedCheckpoint S F h_f →
            B ∈ T.getConfirmed →
            F ≼ T.J ∧ T.isViableBool F = true ∧ F ≼ B

/-- **Order independence** (paper Theorem `thm:orderindep`), observable-store form:
    two parent-first replays of the same block set agree on `F`, `J`, `hj`, `hmax`,
    and on the accepted subtree rooted at finality. They may still differ outside that
    subtree (the paper's `LiveEquivalent` scoping; see the file header). -/
def ParentFirstReplayLiveEquivalentStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {input₁ input₂ : List (StoreEntry n)} {S T : Store n},
        ReplayEntriesOf input₁ S →
          ReplayEntriesOf input₂ T →
          ParentFirstEntries input₁ →
          ParentFirstEntries input₂ →
          (input₁.map StoreEntry.block).Nodup →
          (input₂.map StoreEntry.block).Nodup →
          Block.genesis ∉ input₁.map StoreEntry.block →
          Block.genesis ∉ input₂.map StoreEntry.block →
          InputIdInjective input₁ →
          InputBlockEquivalent input₁ input₂ →
          LiveEquivalent S T

/-- **Order independence** (paper Theorem `thm:orderindep`), `getConfirmed` form: two
    parent-first replays of equivalent input sets agree on the executable
    `getConfirmed` set, even though the raw stores may differ outside the finalized
    subtree. -/
def ParentFirstReplayGetConfirmedStatement (n f : ℕ) : Prop :=
  n = 3 * f + 1 →
    ¬ @AtLeastFThirdSlashable n f →
      ∀ {input₁ input₂ : List (StoreEntry n)} {S T : Store n} {B : Block n},
        ReplayEntriesOf input₁ S →
          ReplayEntriesOf input₂ T →
          ParentFirstEntries input₁ →
          ParentFirstEntries input₂ →
          (input₁.map StoreEntry.block).Nodup →
          (input₂.map StoreEntry.block).Nodup →
          Block.genesis ∉ input₁.map StoreEntry.block →
          Block.genesis ∉ input₂.map StoreEntry.block →
          InputIdInjective input₁ →
          InputBlockEquivalent input₁ input₂ →
          (B ∈ S.getConfirmed ↔ B ∈ T.getConfirmed)

end Store

end DecoupledConsensus
